apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-golang-helloworld
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang-helloworld
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 69
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 120

# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: hpa-golang-helloworld
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: golang-helloworld
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 69
#   #targetMemoryUtilizationPercentage: 120
