
Vagrant.configure("2") do |config|
  config.vm.define "dash" do |dash|
    dash.vm.box = "ubuntu/focal64"
    dash.vm.network "private_network", ip:"193.1.1.4"
      dash.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
     end
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "ubuntu/focal64"
    node01.vm.network "private_network",ip: "193.2.2.2"
      node01.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
     end
  end

  config.vm.define "node02" do |node02|
    node02.vm.box = "ubuntu/focal64"
    node02.vm.network "private_network",ip: "193.2.2.3"
      node02.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
     end
  end

  config.vm.define "node03" do |node03|
    node03.vm.box = "ubuntu/focal64"
    node03.vm.network "private_network",ip: "193.2.2.4"
      node03.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
     end
  end
end